language: perl

env:
  global:
    - PATH=/usr/local/bin:/opt/rakudo-pkg/bin/:/home/travis/.perl6/bin:$PATH
    - SP6_REPO=file:///tmp/repo
    #- SP6_REPO=http://repo.southcentralus.cloudapp.azure.com
    - SKIP_POWERSHELL=1

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 379CE192D401AB61
  - echo "deb https://dl.bintray.com/nxadm/rakudo-pkg-debs `lsb_release -cs` main" | sudo tee -a /etc/apt/sources.list.d/rakudo-pkg.list 
  - sudo apt-get update && sudo apt-get install rakudo-pkg
  #- cpanm -q --notest Carton Template
  - sudo apt-get install libtemplate-perl carton

install:
  - zef install --/test .
  - git clone https://github.com/melezhik/sparrow-plugins && s6 --repo-init /tmp/repo
  - cd sparrow-plugins && git checkout master && git pull origin master
  - find -maxdepth 2 -mindepth 2 -name sparrow.json -execdir s6 --upload \;
  - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install -y powershell
  - cd ../
  - perl6 -MSparrow6::Task::Repository -e "Sparrow6::Task::Repository::Api.new.index-update"

script:
  - ./test.sh

